- name: make apt not installing 'Suggests' and 'Recommends' by default
  file:
    src: /opt/admintools/etc/apt/apt.conf.d/99MinimalInstalls
    dest: /etc/apt/apt.conf.d/99MinimalInstalls
    state: link

- name: disable apt (systemd) timers
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - apt-daily.timer
    - apt-daily-upgrade.timer
  register: apt_timer_service_result
  failed_when: "apt_timer_service_result is failed and 'Could not find the requested service' not in apt_timer_service_result.msg"
