- name: install packages for getting hardware information
  register: install_hw_info_packages_result
  package:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
  with_dict: "{{ system_information_packages
                 | combine(system_information_packages_extra) }}"
