- name: reload fail2ban
  service:
    name: fail2ban
    # fail2ban.service currently (12/2017) does not support reloading,
    # so we restart:
    state: restarted

- name: persist ipv4 tables
  include_tasks: handlers/_persist-iptables.yml
  vars:
    dump_command: iptables-save
    rules_file: /etc/iptables/rules.v4
    rules_backup_file: "{{ rules_file }}.Ansible-backup-{{
     ansible_date_time.iso8601
    }}"

- name: persist ipv6 tables
  include_tasks: handlers/_persist-iptables.yml
  vars:
    dump_command: ip6tables-save
    rules_file: /etc/iptables/rules.v6
    rules_backup_file: "{{ rules_file }}.Ansible-backup-{{
     ansible_date_time.iso8601
    }}"
