# This is the minimum you have to configure to set up a runner:
#
# ```
# gitlab_runners:
#   "my runner":
#     api_url: …
#     registration_token: …
# ```
# for additional supported variables, see ``gitlab_runner_defaults``
# below.
gitlab_runners: {}

# those are the defaults for the GitLab runners configured
gitlab_runner_defaults:

  # Of course, you could also set the API URL and registration token
  # in this directory of defaults:
  #api_url: …
  #registration_token: …

  tag_list: []
  run_untagged: yes
  locked: no
  access_level: not_protected

# How many jobs to run in parallel at max:
gitlab_runners_concurrent: 1

# Divide available memory by the concurrency level but reserve 1G.
gitlab_runners_memory_limit: "{{
  ((ansible_memory_mb.real.total - 1024) /
    gitlab_runners_concurrent) | int
}}m"

# CPU overload is not too bad, so we grant every container to use 95 %
# of the available cores. A more nice calculation would be, e.g.:
# ``(ansible_processor_vcpus - 1) / gitlab_runners_concurrent``.
gitlab_runners_cpus: "{{
  [ansible_processor_vcpus * 0.95, 1] | max | int
}}"
