- name: add delay to cron tasks
  copy:
    dest: /etc/cron.{{ item.key }}/000-delay
    mode: 500
    content: |
      #!/bin/sh
      sleep $(
        python -c 'import random as r; print(
          r.randint({{ item.value.min }}, {{ item.value.max }})
        )'
      )m
  with_dict:
    hourly:
      min: 15
      max: 45
    monthly:
      min: 100
      max: 200
    weekly:
      min: 200
      max: 300
    daily:
      min: 300
      max: 400
