name: merge from master to Debian 8 compatibility branch
on:
  push:
    branches:
      - master

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: merge master -> debian-8-compat
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: debian-8-compat
          github_token: ${{ github.token }}
