- name: remove old fstrim cron entry (now via systemd timer)
  cron:
    name: fstrim
    state: absent

- name: remove old systemd service priorities override files
        (now called ``ansible-priorities.conf``)
  shell: >
    grep -lr Nice /etc/systemd/system
    | egrep 'override|ansible.conf'
    | xargs --no-run-if-empty rm

- name: remove old systemd fstrim override file
  file:
    dest: /etc/systemd/system/fstrim.service.d/override.conf
    state: absent

# 20-03-26
- name: remove firmware updater systemd units overrides
  command: find /etc/systemd -wholename '*fwupd*/ansible.conf' -delete

# 20-06-04
- name: remove renamed sysctl configuration (reboot on panic)
  file:
    dest: /etc/sysctl.d/50-reboot-on-panic.conf
    state: absent

# 20-07
- name: remove /etc/apt/sources.d/*list.list files
  shell: rm -f /etc/apt/sources.d/*list.list
